# -*- coding: utf-8 -*-
"""basic_sine_wave.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1MEmUjNUoxiVAP3iMBJAg1Q1Aup0kl9

### **Sine Wave**
"""

import matplotlib.pyplot as plt
import numpy as np

A = 0.8
f0 = 1000
phi = np.pi/2
fs = 44100
t = np.arange(-0.002,0.002,1.0/fs)

x = A * np.cos (2 * np.pi * f0 * t + phi)

plt.plot(t,x)
plt.axis([-0.002,0.002,-1,1])
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.title('Sine Wave')
plt.show()