# -*- coding: utf-8 -*-
"""complex_sinusoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1veQsgUjzofdoEGaehPNM_SoWv8KcJDLX

### **Sinusoids**
"""

import matplotlib.pyplot as plt
import numpy as np

N = 32
k = 5
n = np.arange(-N/2,N/2)
x = np.exp(1j*2*np.pi*k*n/N)

plt.plot(n,np.real(x))
plt.plot(n,np.imag(x))
plt.axis([-N/2,N/2,-1,1])
plt.xlabel('n')
plt.ylabel('Amplitude')
plt.title('DFT')
plt.show()