# -*- coding: utf-8 -*-
"""DFT_IDFT_implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hA8HSyM5rmlLd6DJ7u4--475-hepdIzI

### **DFT** **and IDFT**
"""

import numpy as np
import matplotlib.pyplot as plt

#Parameters
N = 64
k0 = 7
k01 = 7.5

#Input Functions Whole Number k0
x1 = np.exp(1j * 2 * np.pi * k0 / N * np.arange(N)) #Exponential
x2 = np.cos(2 * np.pi * k0 / N * np.arange(N))      #Cosine

#Input Functions Floating Point k0
x11 = np.exp(1j * 2 * np.pi * k01 / N * np.arange(N)) #Exponential
x21 = np.cos(2 * np.pi * k01 / N * np.arange(N))      #Cosine

#Initializing arrays
X1 = np.array([])
X2 = np.array([])
X11 = np.array([])
X21 = np.array([])
y1 = np.array([])
y2 = np.array([])
y11 = np.array([])
y21 = np.array([])
nv = np.arange(-N/2,N/2)
kv = np.arange(-N/2,N/2)

#Doing the DFT for function x1
for k in range(N):
  s = np.exp(1j * 2 * np.pi * k / N * np.arange(N))
  X1 = np.append(X1 , np.sum(x1 * np.conjugate(s)))

#Doing the DFT for function x2
for k in kv:
  s = np.exp(1j * 2 * np.pi * k / N * nv)
  X2 = np.append(X2 , np.sum(x2 * np.conjugate(s)))

#Doing the DFT for function x11
for k in range(N):
  s = np.exp(1j * 2 * np.pi * k / N * np.arange(N))
  X11 = np.append(X11 , np.sum(x11 * np.conjugate(s)))

#Doing the DFT for function x21
for k in kv:
  s = np.exp(1j * 2 * np.pi * k / N * nv)
  X21 = np.append(X21 , np.sum(x21 * np.conjugate(s)))

#Doing the IDFT for function x1 (including 1/N scaling)
for n in nv:
  s = np.exp(1j * 2 * np.pi * n / N * np.arange(N))
  y1 = np.append(y1 , np.sum(X1 * s) / N)

#Doing the IDFT for function x2 (including 1/N scaling)
for n in nv:
  s = np.exp(1j * 2 * np.pi * n / N * kv)
  y2 = np.append(y2 , np.sum(X2 * s) / N)

#Doing the IDFT for function x11 (including 1/N scaling)
for n in nv:
  s = np.exp(1j * 2 * np.pi * n / N * np.arange(N))
  y11 = np.append(y11 , np.sum(X11 * s) / N)

#Doing the IDFT for function x21 (including 1/N scaling)
for n in nv:
  s = np.exp(1j * 2 * np.pi * n / N * kv)
  y21 = np.append(y21 , np.sum(X21 * s) / N)

# Plotting all 4 plots in a 2x2 grid
fig, axs = plt.subplots(2, 2, figsize=(14, 10))

# 1. DFT Whole Number
axs[0, 0].plot(np.arange(N), abs(X1))
axs[0, 0].plot(kv, abs(X2))
axs[0, 0].text(8, N - 10, 'k = 7')
axs[0, 0].axis([-(N+1)/2, (N-1)/2, 0, N])
axs[0, 0].set_xlabel('k')
axs[0, 0].set_ylabel('Amplitude')
axs[0, 0].set_title('DFT for Whole Number')
axs[0, 0].legend(['Exponential', 'Cosine'], loc='lower left')

# 2. DFT Floating Point
axs[0, 1].plot(np.arange(N), abs(X11))
axs[0, 1].plot(kv, abs(X21))
axs[0, 1].text(9, N/2 + 5, 'k = 7.5')
axs[0, 1].axis([-(N+1)/2, (N-1)/2, 0, N])
axs[0, 1].set_xlabel('k')
axs[0, 1].set_ylabel('Amplitude')
axs[0, 1].set_title('DFT for Floating Point Number')
axs[0, 1].legend(['Exponential', 'Cosine'], loc='lower left')

# 3. IDFT Whole Number
axs[1, 0].plot(nv, np.real(y1))
axs[1, 0].plot(nv, np.real(y2))
axs[1, 0].axis([-N/2, N/2 - 1, -1.2, 1.2])
axs[1, 0].set_xlabel('n')
axs[1, 0].set_ylabel('Amplitude')
axs[1, 0].set_title('IDFT for Whole Number')
axs[1, 0].legend(['Exponential', 'Cosine'], loc='lower left')

# 4. IDFT Floating Point
axs[1, 1].plot(nv, np.real(y11))
axs[1, 1].plot(nv, np.real(y21))
axs[1, 1].axis([-N/2, N/2 - 1, -1.2, 1.2])
axs[1, 1].set_xlabel('n')
axs[1, 1].set_ylabel('Amplitude')
axs[1, 1].set_title('IDFT for Floating Point Number')
axs[1, 1].legend(['Exponential', 'Cosine'], loc='lower left')

plt.tight_layout()
plt.show()